name: Deploy via FTP

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Install Composer depedencies
        uses: ramsey/composer-install@1.1.0
      - name: Upload ftp 
        uses: sand4rt/ftp-deployer@v1.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote-folder: ./public_html
          clean_up: true
